In [3]:
# Question 1: Read in an image from a file
# Prompt: "Write a Python program to read in an image from a file"

# ChatGPT response code:
from PIL import Image

# Open the image file
with Image.open("image.jpg") as im:
    # Display the image
    im.show()

In [7]:
# Question 2: Resize an image
# Prompt: "Now, I would like you to write a Python program that resizes an arbitrary input image to have dimensions 256x256"

# ChatGPT response
import cv2

# Read in the image
im = cv2.imread("image.jpg")

# Resize the image
im_resized = cv2.resize(im, (256, 256))

# Save the resized image
cv2.imwrite("image_resized.jpg", im_resized)

True

In [9]:
# Question 3: Rotate and image
# Prompt: Using the openCV library, write a program which rotates an image and then saves it

# ChatGPT response:
import cv2
import numpy as np

# Read in the image
im = cv2.imread("image.jpg")

# Get the image height and width
(h, w) = im.shape[:2]

# Define the center of the image
center = (w / 2, h / 2)

# Define the angle of rotation (in degrees)
angle = 90

# Define the scale of the image
scale = 1.0

# Perform the rotation
rotation_matrix = cv2.getRotationMatrix2D(center, angle, scale)
rotated_image = cv2.warpAffine(im, rotation_matrix, (w, h))

# Save the rotated image
cv2.imwrite("image_rotated.jpg", rotated_image)

True

In [13]:
# Question 4: Sharpen an image
# Prompt: Using the openCV library, write a program to sharpen an image and then save it

import cv2
import numpy as np

# Load the image
image = cv2.imread('image_blurred.jpg')

# Create the sharpening kernel, it must be odd
kernel_sharpening = np.array([[-1,-1,-1], 
                              [-1, 9,-1], 
                              [-1,-1,-1]])

# Apply the kernel to the image
sharpened = cv2.filter2D(image, -1, kernel_sharpening)

# Save the sharpened image
cv2.imwrite('image_sharpened.jpg', sharpened)


True

In [11]:
# Question 5: Blur an image
# Prompt: Using the openCV library, write a program to blur an image

# ChatGPT response
import cv2

# Load the image
image = cv2.imread('image.jpg')

# Blur the image using a Gaussian filter
image_blurred = cv2.GaussianBlur(image, (10, 10), 0)

# Save the blurred image
cv2.imwrite('image_blurred.jpg', image_blurred)

error: OpenCV(4.6.0) /private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_562_cazh1h/croots/recipe/opencv-suite_1664548333142/work/modules/imgproc/src/smooth.dispatch.cpp:294: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'createGaussianKernels'


In [1]:
# Question 6: Convert a color image into a greyscale image
# Prompt: Using Python, convert a color image into a greyscale image

# ChatGPT response
import cv2

# Load the color image
image = cv2.imread('image.jpg')

# Convert the image to grayscale
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Save the grayscale image
cv2.imwrite('grayscale_image.jpg', gray_image)

True

In [2]:
# Question 7: Detect edges

# Load the image
image = cv2.imread('image.jpg')

# Convert the image to grayscale
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Apply the Canny edge detection algorithm
edges = cv2.Canny(gray_image, 100, 200)

# Save the edge image
cv2.imwrite('edges.jpg', edges)

True

In [12]:
# Question 8: Detect faces

import cv2

# Load the cascade classifier
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

# Load the input image
img = cv2.imread("faces_input.jpg")

# Convert the input image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Detect faces in the grayscale image
faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5)

# Draw rectangles around the faces
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 2)

# Save the result to an output image
cv2.imwrite("faces_output.jpg", img)

True

In [14]:
# Detect cars

import cv2
import numpy as np

# Load the HOG descriptor
hog = cv2.HOGDescriptor()
hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())

# Load the input image
img = cv2.imread("cars.jpg")

# Run the HOG descriptor on the input image to detect cars
boxes, weights = hog.detectMultiScale(img, winStride=(8, 8), padding=(32, 32), scale=1.05)

# Draw rectangles around the detected cars
for (x, y, w, h) in boxes:
    cv2.rectangle(img, (x, y), (x + w, y + h), (0, 0, 255), 2)

# Save the result to an output image
cv2.imwrite("cars_output.jpg", img)

True

In [16]:
# Classify dog vs. cat

import tensorflow as tf
import numpy as np
import cv2

# Download the pre-trained deep learning model
url = "https://github.com/tensorflow/tensorflow/blob/r2.4/tensorflow/lite/examples/images/dog_vs_cat_model.tflite?raw=true"
model = tf.keras.models.load_model(url)

# Load the input image
img = cv2.imread("dog.jpg")
img = cv2.resize(img, (224, 224))
img = np.reshape(img, [1, 224, 224, 3])

# Perform prediction using the deep learning model
prediction = model.predict(img)

# Get the class label with the highest predicted probability
class_index = np.argmax(prediction[0])
class_label = "dog" if class_index == 1 else "cat"

# Print the prediction result
print("The image is of a", class_label)

UnimplementedError: File system scheme 'http' not implemented (file: 'http://github.com/tensorflow/tensorflow/blob/r2.4/tensorflow/lite/examples/images/dog_vs_cat_model.tflite?raw=true')

In [21]:
a = np.array([[4,2,3,7],
              [3,5,2,1],
              [1,9,4,2]])

b = np.array([[2,7,6],
              [1,3,2],
              [4,5,1]])

q1 = b@a
q2 = (a.T@b).T

print(q1)
print(q2)
print(np.subtract(q1, q2))

[[35 93 44 33]
 [15 35 17 14]
 [32 42 26 35]]
[[15 45 24 23]
 [42 74 47 62]
 [31 31 26 46]]
[[ 20  48  20  10]
 [-27 -39 -30 -48]
 [  1  11   0 -11]]
